VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet6"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Private Sub CmdBack_Click()
Call goStoD("Input", "ShPivot")
End Sub

Private Sub CmdHelp_Click()
Call HelpJarvis
End Sub

Private Sub CmdNext_Click()

Call goStoD("Input", "ShPivot")

End Sub

Private Sub CommandButton1_Click()

End Sub
